"""baseline schema

Revision ID: 711fd5e3f1e8
Revises:
Create Date: 2026-06-14 16:11:35.183279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import database.models  # кастомный тип SafeArray, на который ссылается autogenerate

# revision identifiers, used by Alembic.
revision: str = "711fd5e3f1e8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_conversations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column(
            "content", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("tool_use_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "role IN ('user','assistant','tool_use','tool_result')", name="agent_conversations_role_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_agent_conv_source",
        "agent_conversations",
        ["source"],
        unique=False,
        postgresql_where=sa.text("source IS NOT NULL"),
    )
    op.create_index(
        "idx_agent_conv_user_created",
        "agent_conversations",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("db_user", sa.Text(), nullable=False),
        sa.Column("query_type", sa.Text(), nullable=False),
        sa.Column("table_name", sa.Text(), nullable=True),
        sa.Column("query_excerpt", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_ts", "audit_log", [sa.literal_column("ts DESC")], unique=False)
    op.create_index("idx_audit_user_table", "audit_log", ["db_user", "table_name"], unique=False)
    op.create_table(
        "llm_usage_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_creation_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), server_default="0", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_llm_usage_created", "llm_usage_log", [sa.literal_column("created_at DESC")], unique=False)
    op.create_index(
        "idx_llm_usage_purpose", "llm_usage_log", ["purpose", sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index(
        "idx_llm_usage_user", "llm_usage_log", ["user_id", sa.literal_column("created_at DESC")], unique=False
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=True),
        sa.Column("role", sa.String(length=50), server_default="user", nullable=True),
        sa.Column("registered_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=50), server_default="Europe/Moscow", nullable=True),
        sa.Column("health_token", sa.String(length=255), nullable=True),
        sa.Column("share_token", sa.String(length=64), nullable=True),
        sa.Column("garmin_email", sa.String(length=255), nullable=True),
        sa.Column("garmin_password", sa.String(length=255), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("height_cm", sa.SmallInteger(), nullable=True),
        sa.Column("sex", sa.String(length=10), server_default="male", nullable=True),
        sa.Column("smoking_status", sa.String(length=20), nullable=True),
        sa.Column("bmr", sa.Float(), nullable=True),
        sa.Column("avg_active_calories", sa.Float(), nullable=True),
        sa.Column("target_weight_kg", sa.Float(), nullable=True),
        sa.Column("cohort", sa.String(length=20), server_default="external", nullable=False),
        sa.Column("container_id", sa.String(length=50), nullable=True),
        sa.Column("container_port", sa.Integer(), nullable=True),
        sa.Column("pack_name", sa.String(length=50), server_default="generic", nullable=False),
        sa.Column("jwt_secret", sa.String(length=64), nullable=True),
        sa.Column("encrypted_openai_key", sa.Text(), nullable=True),
        sa.Column("encrypted_anthropic_key", sa.Text(), nullable=True),
        sa.Column("agent_system_prompt", sa.Text(), nullable=True),
        sa.Column("agent_review_consent", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("onboarding_step", sa.String(length=30), server_default="done", nullable=True),
        sa.Column(
            "onboarding_data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default="{}",
            nullable=True,
        ),
        sa.Column("kb_status", sa.String(length=20), nullable=True),
        sa.CheckConstraint("cohort IN ('owner','family','early_user','external')", name="users_cohort_check"),
        sa.CheckConstraint("kb_status IS NULL OR kb_status IN ('shared','private','none')", name="ck_kb_status"),
        sa.CheckConstraint(
            "pack_name IN ('generic','cardiac','bariatric','female-cycle','respiratory_allergic')",
            name="users_pack_name_check",
        ),
        sa.PrimaryKeyConstraint("telegram_id"),
        sa.UniqueConstraint("health_token"),
        sa.UniqueConstraint("share_token"),
    )
    op.create_table(
        "activity_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("active_calories", sa.Float(), nullable=True),
        sa.Column("total_calories", sa.Float(), nullable=True),
        sa.Column("bmr_calories", sa.Float(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("heart_rate_avg", sa.Integer(), nullable=True),
        sa.Column("hrv", sa.Integer(), nullable=True),
        sa.Column("stress_level", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), server_default="apple_health", nullable=True),
        sa.Column(
            "raw_data", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="activity_log_user_id_date_key"),
    )
    op.create_index("idx_activity_user_date", "activity_log", ["user_id", "date"], unique=False)
    op.create_table(
        "blood_pressure_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("systolic", sa.Integer(), nullable=False),
        sa.Column("diastolic", sa.Integer(), nullable=False),
        sa.Column("heart_rate", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "measured_at", name="blood_pressure_logs_user_id_measured_at_key"),
    )
    op.create_index(
        "idx_bp_user_date", "blood_pressure_logs", ["user_id", sa.literal_column("measured_at DESC")], unique=False
    )
    op.create_table(
        "blood_tests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("test_date", sa.Date(), nullable=False),
        sa.Column("test_type", sa.String(length=100), nullable=True),
        sa.Column(
            "values", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), server_default="current", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "blood_tests_user_date_type_unique", "blood_tests", ["user_id", "test_date", "test_type"], unique=True
    )
    op.create_index("idx_blood_tests_user_date", "blood_tests", ["user_id", "test_date"], unique=False)
    op.create_table(
        "body_measurements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("waist_cm", sa.Float(), nullable=True),
        sa.Column("neck_cm", sa.Float(), nullable=True),
        sa.Column("hips_cm", sa.Float(), nullable=True),
        sa.Column("chest_cm", sa.Float(), nullable=True),
        sa.Column("thigh_cm", sa.Float(), nullable=True),
        sa.Column("biceps_cm", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_measurements_user_date", "body_measurements", ["user_id", "measured_at"], unique=False)
    op.create_table(
        "daily_summaries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total_calories", sa.Integer(), nullable=True),
        sa.Column("total_protein", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("total_fats", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("total_carbs", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("had_workout", sa.Boolean(), nullable=True),
        sa.Column("sleep_hours", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("bp_systolic", sa.Integer(), nullable=True),
        sa.Column("bp_diastolic", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="daily_summaries_user_id_date_key"),
    )
    op.create_index(
        "idx_summaries_user_date", "daily_summaries", ["user_id", sa.literal_column("date DESC")], unique=False
    )
    op.create_table(
        "nutrition_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("meal_time", sa.Time(), nullable=True),
        sa.Column("meal_name", sa.String(length=255), nullable=True),
        sa.Column(
            "items", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "totals", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("photo_paths", database.models.SafeArray(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "date", "meal_time", "meal_name", name="nutrition_log_user_id_date_meal_time_meal_name_key"
        ),
    )
    op.create_index("idx_nutrition_user_date", "nutrition_log", ["user_id", "date"], unique=False)
    op.create_table(
        "sleep_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sleep_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_hours", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column("deep_sleep_minutes", sa.Integer(), nullable=True),
        sa.Column("rem_sleep_minutes", sa.Integer(), nullable=True),
        sa.Column("light_sleep_minutes", sa.Integer(), nullable=True),
        sa.Column("awake_minutes", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sleep_user_date", "sleep_records", ["user_id", sa.literal_column("date DESC")], unique=False)
    op.create_table(
        "supplements_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=True),
        sa.Column("supplement_name", sa.String(length=255), nullable=False),
        sa.Column("dosage", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_supplements_user_date", "supplements_log", ["user_id", "date"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("show_calorie_budget_bar", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("bmr_source", sa.String(length=10), server_default="auto", nullable=False),
        sa.Column("bmr_override", sa.Integer(), nullable=True),
        sa.Column("activity_avg_override", sa.Integer(), nullable=True),
        sa.Column("activity_level", sa.String(length=20), nullable=True),
        sa.Column("target_weight_kg", sa.Float(), nullable=True),
        sa.Column("target_weight_date", sa.Date(), nullable=True),
        sa.Column("calorie_goal_pct", sa.Integer(), server_default="-15", nullable=False),
        sa.Column("supplement_reminders_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("supplement_reminder_time", sa.Time(), server_default="08:00:00", nullable=False),
        sa.Column(
            "supplements",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "weights",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("body_fat", sa.Float(), nullable=True),
        sa.Column("muscle_mass", sa.Float(), nullable=True),
        sa.Column("water", sa.Float(), nullable=True),
        sa.Column("bmi", sa.Float(), nullable=True),
        sa.Column("visceral_fat", sa.Integer(), nullable=True),
        sa.Column("bone_mass", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "measured_at", name="weights_user_id_measured_at_key"),
    )
    op.create_index("idx_weights_user_date", "weights", ["user_id", "measured_at"], unique=False)
    op.create_table(
        "workouts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("workout_type", sa.String(length=100), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("calories_burned", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("distance_km", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_workouts_user_date", "workouts", ["user_id", sa.literal_column("date DESC")], unique=False)
    # ### end Alembic commands ###

    # --- RLS: роль hv_app + изоляция по user_id (#83) ---
    # autogenerate не видит роли/политики/гранты — перенесено вручную из прод-схемы.
    # hv_app — login-роль приложения: RLS применяется к ней, владелец healthvault её обходит.
    # Пароль роли задаётся оператором вне миграции (секрет) — здесь только наличие роли.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hv_app') THEN
                CREATE ROLE hv_app LOGIN;
            END IF;
        END
        $$;
        """
    )
    op.execute(
        """
        GRANT USAGE ON SCHEMA public TO hv_app;

        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE activity_log TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE activity_log_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE agent_conversations TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE agent_conversations_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE audit_log TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE audit_log_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE blood_pressure_logs TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE blood_pressure_logs_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE blood_tests TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE blood_tests_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE body_measurements TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE body_measurements_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE daily_summaries TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE daily_summaries_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE llm_usage_log TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE llm_usage_log_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE nutrition_log TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE nutrition_log_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE sleep_records TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE sleep_records_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE supplements_log TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE supplements_log_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE user_settings TO hv_app;
        GRANT SELECT ON TABLE users TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE weights TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE weights_id_seq TO hv_app;
        GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE workouts TO hv_app;
        GRANT SELECT,USAGE ON SEQUENCE workouts_id_seq TO hv_app;

        ALTER DEFAULT PRIVILEGES FOR ROLE healthvault IN SCHEMA public
            GRANT SELECT,USAGE ON SEQUENCES TO hv_app;
        ALTER DEFAULT PRIVILEGES FOR ROLE healthvault IN SCHEMA public
            GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO hv_app;

        ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
        ALTER TABLE agent_conversations ENABLE ROW LEVEL SECURITY;
        ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
        ALTER TABLE blood_pressure_logs ENABLE ROW LEVEL SECURITY;
        ALTER TABLE nutrition_log ENABLE ROW LEVEL SECURITY;
        ALTER TABLE supplements_log ENABLE ROW LEVEL SECURITY;
        ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
        ALTER TABLE weights ENABLE ROW LEVEL SECURITY;

        CREATE POLICY agent_conversations_self ON agent_conversations
            USING (((current_setting('app.user_id'::text, true) = ''::text)
                OR ((current_setting('app.user_id'::text, true))::bigint = user_id)));
        CREATE POLICY audit_admin_only ON audit_log TO hv_app USING (false);
        CREATE POLICY user_isolation ON activity_log TO hv_app
            USING ((user_id = (NULLIF(current_setting('app.user_id'::text, true), ''::text))::bigint));
        CREATE POLICY user_isolation ON blood_pressure_logs TO hv_app
            USING ((user_id = (NULLIF(current_setting('app.user_id'::text, true), ''::text))::bigint));
        CREATE POLICY user_isolation ON nutrition_log TO hv_app
            USING ((user_id = (NULLIF(current_setting('app.user_id'::text, true), ''::text))::bigint));
        CREATE POLICY user_isolation ON supplements_log TO hv_app
            USING ((user_id = (NULLIF(current_setting('app.user_id'::text, true), ''::text))::bigint));
        CREATE POLICY user_isolation ON user_settings TO hv_app
            USING ((user_id = (NULLIF(current_setting('app.user_id'::text, true), ''::text))::bigint));
        CREATE POLICY user_isolation ON weights TO hv_app
            USING ((user_id = (NULLIF(current_setting('app.user_id'::text, true), ''::text))::bigint));
        """
    )


def downgrade() -> None:
    # Снять default-privileges (политики/RLS/табличные гранты уйдут с дропом таблиц).
    # Роль hv_app не дропаем — она кластерная и может использоваться вне этой БД.
    op.execute(
        """
        ALTER DEFAULT PRIVILEGES FOR ROLE healthvault IN SCHEMA public
            REVOKE SELECT,USAGE ON SEQUENCES FROM hv_app;
        ALTER DEFAULT PRIVILEGES FOR ROLE healthvault IN SCHEMA public
            REVOKE SELECT,INSERT,DELETE,UPDATE ON TABLES FROM hv_app;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_workouts_user_date", table_name="workouts")
    op.drop_table("workouts")
    op.drop_index("idx_weights_user_date", table_name="weights")
    op.drop_table("weights")
    op.drop_table("user_settings")
    op.drop_index("idx_supplements_user_date", table_name="supplements_log")
    op.drop_table("supplements_log")
    op.drop_index("idx_sleep_user_date", table_name="sleep_records")
    op.drop_table("sleep_records")
    op.drop_index("idx_nutrition_user_date", table_name="nutrition_log")
    op.drop_table("nutrition_log")
    op.drop_index("idx_summaries_user_date", table_name="daily_summaries")
    op.drop_table("daily_summaries")
    op.drop_index("idx_measurements_user_date", table_name="body_measurements")
    op.drop_table("body_measurements")
    op.drop_index("idx_blood_tests_user_date", table_name="blood_tests")
    op.drop_index("blood_tests_user_date_type_unique", table_name="blood_tests")
    op.drop_table("blood_tests")
    op.drop_index("idx_bp_user_date", table_name="blood_pressure_logs")
    op.drop_table("blood_pressure_logs")
    op.drop_index("idx_activity_user_date", table_name="activity_log")
    op.drop_table("activity_log")
    op.drop_table("users")
    op.drop_index("idx_llm_usage_user", table_name="llm_usage_log")
    op.drop_index("idx_llm_usage_purpose", table_name="llm_usage_log")
    op.drop_index("idx_llm_usage_created", table_name="llm_usage_log")
    op.drop_table("llm_usage_log")
    op.drop_index("idx_audit_user_table", table_name="audit_log")
    op.drop_index("idx_audit_ts", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index("idx_agent_conv_user_created", table_name="agent_conversations")
    op.drop_index(
        "idx_agent_conv_source", table_name="agent_conversations", postgresql_where=sa.text("source IS NOT NULL")
    )
    op.drop_table("agent_conversations")
    # ### end Alembic commands ###
